server:
  port: 8080
  servlet:
    context-path: /task-manager

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task_manager?useSSL=false&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

app:
  jwt:
    secret: your-256-bit-secret-key-here-must-be-32-chars
    expiration: 86400000 # 24 hours in milliseconds